import os
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
# import uuid # Needed for unique user IDs temp update
from database import *
from fpdf import FPDF

create_table()

# --- USER AUTHENTICATION LOGIC ---
if "logged_in" not in st.session_state:
    st.session_state["logged_in"] = False
    st.session_state["username"] = ""

def login_screen():
    st.sidebar.title("🔐 User Login")
    choice = st.sidebar.selectbox("Login/Signup", ["Login", "Sign Up"])
    
    if choice == "Login":
        user = st.sidebar.text_input("Username")
        passwd = st.sidebar.text_input("Password", type='password')
        if st.sidebar.button("Login"):
            result = login_user(user, passwd)
            if result:
                st.session_state["logged_in"] = True
                st.session_state["username"] = user
                st.rerun()
            else:
                st.sidebar.error("Invalid Username/Password")
                
    else:
        new_user = st.sidebar.text_input("Create Username")
        new_passwd = st.sidebar.text_input("Create Password", type='password')
        if st.sidebar.button("Sign Up"):
            try:
                add_user(new_user, new_passwd)
                st.sidebar.success("Account created! Please Login.")
            except:
                st.sidebar.error("Username already exists.")

# Main Control: Stop the app if not logged in
if not st.session_state["logged_in"]:
    st.set_page_config(page_title="Spendl - Login", layout="centered")
    st.title("[ S P E N D L ] - Expense Tracker App")
    login_screen()
    st.info("Welcome to Spendl. Please log in or create an account to start tracking your expenses.")
    st.stop() 

# Define the user for all database queries
current_user = st.session_state["username"]

# --- BRANDING CONFIGURATION --- NEW UPDATE
COMPANY_NAME = "Spendl"
LOGO_PATH = "logo.png"  # Ensure this file exists in your directory
PRIMARY_COLOR = (41, 128, 185)  # Professional Blue (RGB)
SECONDARY_COLOR = (52, 73, 94)  # Dark Gray (RGB)

# Create chart image functions helper functions NEW UPDATE
def save_category_pie_chart(df):
    fig, ax = plt.subplots()
    df.groupby("Category")["Amount"].sum().plot(
        kind="pie", autopct="%1.1f%%", ax=ax
    )
    ax.set_ylabel("")
    plt.tight_layout()
    fig.savefig("category_chart.png")
    plt.close(fig)


def save_monthly_bar_chart(df):
    df["Month"] = df["Date"].dt.to_period("M").astype(str)
    monthly = df.groupby("Month")["Amount"].sum().sort_index()

    fig, ax = plt.subplots()
    ax.bar(monthly.index, monthly.values)
    ax.set_xlabel("Month")
    ax.set_ylabel("Total Expense")
    plt.xticks(rotation=45)
    plt.tight_layout()
    fig.savefig("monthly_chart.png")
    plt.close(fig)


def save_trend_line_chart(df):
    daily = df.groupby("Date")["Amount"].sum().sort_index()

    fig, ax = plt.subplots()
    ax.plot(daily.index, daily.values, marker="o")
    ax.set_xlabel("Date")
    ax.set_ylabel("Total Expense")
    plt.xticks(rotation=45)
    plt.tight_layout()
    fig.savefig("trend_chart.png")
    plt.close(fig)

# --- BRANDED PDF CLASS --- NEW UPDATE
class BrandedPDF(FPDF):
    def header(self):
        if os.path.exists(LOGO_PATH):
            self.image(LOGO_PATH, 10, 8, 33)
        self.set_font("Arial", "B", 15)
        self.set_text_color(*PRIMARY_COLOR)
        self.cell(80)
        self.cell(30, 10, f"{COMPANY_NAME} - Expense Report", 0, 0, "C")
        self.ln(20)
        # Horizontal line
        self.set_draw_color(*PRIMARY_COLOR)
        self.line(10, 30, 200, 30)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()} | User: {current_user}", 0, 1, "C")
        self.cell(0, 5, f"Generated by {COMPANY_NAME}", 0, 0, "C")

def generate_dashboard_pdf(df):
    pdf = BrandedPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    # Title Section
    pdf.set_font("Arial", "B", 16)
    pdf.set_text_color(*SECONDARY_COLOR)
    pdf.cell(0, 10, f"Expense Summary for {current_user}", ln=True)
    pdf.set_font("Arial", "", 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 8, f"Report Date: {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M')}", ln=True)
    pdf.cell(0, 8, f"Total Expenditure: Rs. {df['Amount'].sum():.2f}", ln=True)
    pdf.ln(10)

    # Table Header
    pdf.set_fill_color(*PRIMARY_COLOR)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Arial", "B", 10)
    pdf.cell(40, 10, "Date", 1, 0, "C", 1)
    pdf.cell(50, 10, "Category", 1, 0, "C", 1)
    pdf.cell(60, 10, "Description", 1, 0, "C", 1)
    pdf.cell(40, 10, "Amount (Rs)", 1, 1, "C", 1)

    # Table Data
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", "", 9)
    for _, row in df.iterrows():
        pdf.cell(40, 8, str(row['Date'].date()), 1)
        pdf.cell(50, 8, str(row['Category']), 1)
        pdf.cell(60, 8, str(row['Description'])[:30], 1)
        pdf.cell(40, 8, f"{row['Amount']:.2f}", 1, 1, "R")

    # Visualizations
    save_category_pie_chart(df)
    save_monthly_bar_chart(df)
    save_trend_line_chart(df)

    for title, description, img in [
        ("Category Breakdown", "An overview of spending by category.", "category_chart.png"),
        ("Monthly Trends", "A month-by-month analysis of activity.", "monthly_chart.png"),
        ("Daily Activity", "Detailed daily usage statistics.", "trend_chart.png")
    ]:
        pdf.add_page()
        pdf.set_font("Arial", "B", 14)
        pdf.set_text_color(*SECONDARY_COLOR)
        pdf.cell(0, 10, title, ln=True, align="C")
        pdf.ln(5)
        pdf.image(img, x=25, w=160)

    pdf.output("expense_dashboard.pdf")

    # Cleanup
    for img in ["category_chart.png", "monthly_chart.png", "trend_chart.png"]:
        if os.path.exists(img): os.remove(img)

# ---------------- STREAMLIT UI ---------------- 
# create_table() # Ensure your DB has a session_id column now!
st.set_page_config(page_title="Spendl - Expense Tracker App", layout="wide")

# Sidebar Account Management
st.sidebar.markdown(f"**Logged in as:** `{current_user}`")
if st.sidebar.button("Logout"):
    st.session_state["logged_in"] = False
    st.session_state["username"] = ""
    st.rerun()

# Add title
st.title("[ S P E N D L ]")
st.title("💰Expense Tracker Dashboard")
# Add subtitle
st.markdown("Spending made simple. Track and visualize your expenses easily!")
st.info(f"Session Active: {current_user[:8]} (Data persists in this tab only)") #temp update
st.caption(f"Your Session ID: `{current_user[:13]}...`") #temp update

# ---------------- ADD EXPENSE ----------------
st.sidebar.header("➕ Add Expenses")
date = st.sidebar.date_input("Date")
category = st.sidebar.selectbox("Category", ["Food", "Rent", "Travel", "Shopping", "Bills", "Other"])
description = st.sidebar.text_input("Description")
amount = st.sidebar.number_input("Amount", min_value=0.0)

if st.sidebar.button("Add Expense"):
    # Pass the current_user ID to your database function
    add_expense(str(date), category, description, amount, current_user) # temp update
    st.sidebar.success("Expense Added!")
    st.rerun() #temp update

# ---------------- LOAD DATA ----------------
# Filter data by the current session ID in the database call temp update
data = get_expenses(current_user)
df = pd.DataFrame(data, columns=["ID", "Date", "Category", "Description", "Amount", "Username"]) #temp update
# Ensure Date & Amount types are correct NEW UPDATE
df["Amount"] = pd.to_numeric(df["Amount"], errors="coerce")
df["Date"] = pd.to_datetime(df["Date"])

filtered_df = df.copy() #new update

# ---------------- FILTERS ----------------
# ---------------- DISPLAY CONTENT ----------------
if not df.empty:
    st.subheader("📋 Your Records")
    col1, col2 = st.columns(2)
    with col1:
        selected_category = st.selectbox("Filter by Category", ["All"] + df["Category"].unique().tolist())
    with col2:
        selected_month = st.selectbox("Filter by Month", ["All"] + sorted(df["Date"].dt.strftime("%Y-%m").unique().tolist()))

    filtered_df = df.copy()
    if selected_category != "All":
        filtered_df = filtered_df[filtered_df["Category"] == selected_category]
    if selected_month != "All":
        filtered_df = filtered_df[filtered_df["Date"].dt.strftime("%Y-%m") == selected_month]
    
    filtered_df["Month"] = filtered_df["Date"].dt.to_period("M").astype(str)

    st.dataframe(filtered_df.drop(columns=["Username"]), use_container_width=True)

# ---------------- DELETE ----------------
# Delete Section
    with st.expander("🗑️ Delete a Record"):
        delete_id = st.number_input("Enter Record ID", min_value=1, step=1)
        if st.button("Permanently Delete"):
            delete_expense(delete_id, current_user)
            st.rerun()

# ---------------- SUMMARY ----------------
st.subheader("📊 Summary")
total_expense = filtered_df["Amount"].sum() if not filtered_df.empty else 0.0
st.metric("Total Expense", f"Rs. {total_expense:.2f}")

# ---------------- CHARTS ----------------
# NEW UPDATE
st.divider() 

# --- ROW 1: Two Columns ---
row1_col1, row1_col2 = st.columns(2)

with row1_col1:
    st.subheader("📈 Category-wise Expense Chart")

    if not filtered_df.empty:
        # Define a consistent figure size
        fig, ax = plt.subplots(figsize=(6, 4))
        
        (
            filtered_df
            .groupby("Category")["Amount"]
            .sum()
            .plot(
                kind="pie", 
                autopct="%1.1f%%", 
                ax=ax,
                # Reduce font size of percentages
                textprops={'fontsize': 8}, 
                # Moves percentages slightly further from center to avoid crowding
                pctdistance=0.75, 
                # Moves category names slightly further out
                labeldistance=1.1 
            )
        )
        ax.set_ylabel("")
        st.pyplot(fig)
    else:
        st.info("No data available for selected filters.")

with row1_col2:
    st.subheader("📅 Monthly Expense Trend")
    if not filtered_df.empty:
        monthly_summary = filtered_df.groupby("Month")["Amount"].sum().sort_index()
        fig, ax = plt.subplots(figsize=(6, 5.5))
        ax.bar(monthly_summary.index, monthly_summary.values)
        ax.set_xlabel("Month")
        ax.set_ylabel("Total Expense")
        plt.xticks(rotation=45)
        st.pyplot(fig)
    else:
        st.info("No data available.")

# --- ROW 2: One Chart (Aligned to the left column) ---
row2_col1, row2_col2 = st.columns(2) # Create 2 columns again to keep width the same

with row2_col1:
    st.subheader("📉 Expense Trend Over Time")
    if not filtered_df.empty and len(filtered_df) > 1:
        daily_trend = filtered_df.groupby("Date")["Amount"].sum().sort_index()
        fig, ax = plt.subplots(figsize=(6, 4.5)) # Same figsize as above
        ax.plot(daily_trend.index, daily_trend.values, marker="o")
        ax.set_xlabel("Date")
        ax.set_ylabel("Total Expense")
        plt.xticks(rotation=45)
        st.pyplot(fig)
    else:
        st.info("Not enough data for trend line.")


# ---------------- PDF DOWNLOAD ----------------
def generate_pdf(df):
    pdf = FPDF()
    pdf.add_page()
    
    # --- HEADER SECTION ---
    pdf.set_font("Arial", "B", 16)
    pdf.set_text_color(41, 128, 185)  # Professional Blue
    pdf.cell(0, 10, txt="EXPENSE SUMMARY REPORT", ln=True, align="C")
    
    pdf.set_font("Arial", "I", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, txt=f"User: {current_user} | Date: {pd.Timestamp.now().strftime('%Y-%m-%d')}", ln=True, align="C")
    pdf.ln(5)

    # --- TABLE SETTINGS ---
    pdf.set_font("Arial", "B", 10)
    pdf.set_fill_color(41, 128, 185)  # Header Background
    pdf.set_text_color(255, 255, 255)  # White Text
    
    # Define Column Widths (Total ~190 for A4)
    w_date = 35
    w_cat = 40
    w_desc = 75
    w_amt = 40

    # Table Headers
    pdf.cell(w_date, 10, "Date", border=1, align="C", fill=True)
    pdf.cell(w_cat, 10, "Category", border=1, align="C", fill=True)
    pdf.cell(w_desc, 10, "Description", border=1, align="C", fill=True)
    pdf.cell(w_amt, 10, "Amount (Rs)", border=1, align="C", fill=True)
    pdf.ln()

    # --- TABLE BODY ---
    pdf.set_font("Arial", "", 9)
    pdf.set_text_color(0, 0, 0)
    
    fill = False  # Track alternating rows
    for _, row in df.iterrows():
        # Set light grey background for alternating rows
        if fill:
            pdf.set_fill_color(245, 245, 245)
        else:
            pdf.set_fill_color(255, 255, 255)

        pdf.cell(w_date, 8, str(row['Date'].date()), border=1, align="C", fill=True)
        pdf.cell(w_cat, 8, str(row['Category']), border=1, align="L", fill=True)
        # Truncate long descriptions to fit cell
        desc = str(row['Description'])[:40] + ".." if len(str(row['Description'])) > 40 else str(row['Description'])
        pdf.cell(w_desc, 8, desc, border=1, align="L", fill=True)
        pdf.cell(w_amt, 8, f"{row['Amount']:,.2f}", border=1, align="R", fill=True)
        pdf.ln()
        fill = not fill

    # --- TOTAL SECTION ---
    pdf.ln(2)
    pdf.set_font("Arial", "B", 10)
    pdf.set_fill_color(230, 230, 230)
    pdf.cell(w_date + w_cat + w_desc, 10, "TOTAL EXPENDITURE", border=1, align="R", fill=True)
    pdf.set_text_color(200, 0, 0) # Red for total
    pdf.cell(w_amt, 10, f"Rs. {df['Amount'].sum():,.2f}", border=1, align="R", fill=True)

    pdf.output("expense_report.pdf")

if st.button("📥 Download PDF Report"):
    generate_pdf(filtered_df)
    with open("expense_report.pdf", "rb") as file:
        st.download_button(
            label="Download Expense PDF",
            data=file,
            file_name=f"{current_user}_Expense_Report.pdf",
            mime="application/pdf"
        )
        
# PDF Generator (with charts) NEW UPDATE
st.subheader("📄 Export Branded Dashboard")
if not filtered_df.empty:
    if st.button("📥 Download Branded PDF Report"):
        generate_dashboard_pdf(filtered_df)
        with open("expense_dashboard.pdf", "rb") as file:
            st.download_button(
                label="Click here to download",
                data=file,
                file_name=f"{current_user}_Expense_Report_{pd.Timestamp.now().strftime('%Y%m%d')}.pdf",
                mime="application/pdf"
            )
else:
    st.info("No data available to export.")


# Add Footer
st.markdown("---")
st.markdown("Developed by Garvit Rastogi❤️ | [GitHub](https://github.com/GarvitRastogi978) | [LinkedIn](https://www.linkedin.com/in/garvit-rastogi/)")